### ISSUE TITLE
Just a suggestion 

### ISSUE THREAD

**Issue by Dheerajmadhukar** [s0rg/crawley#95]
1) For latest release, the current download URL for binary is:
https://github.com/s0rg/crawley/releases/latest/download/crawley_v1.7.7_$(uname)_$(uname%20-m).tar.gz
if possible please rename all the release binary files from **"crawley_v1.7.7_$(uname)_$(uname%20-m).tar.gz"** to **"crawley_$(uname)_$(uname -m).tar.gz"** (without the version), it will be easy to download from a single URL for example:
eg: wget https://github.com/s0rg/crawley/releases/latest/download/crawley_$(uname)_$(uname -m).tar.gz

2) Also add "go install -v https://github.com/s0rg/crawley/cmd/crawley@latest" for clean package path download/setup.

**Comment by s0rg** [comment]
1. Use https://github.com/s0rg/crawley/releases/latest to obtain latest tag and download links
2. Use: `go install -v github.com/s0rg/crawley/cmd/crawley@latest` - without `http://`
